enableGlobalCache: false

enableTelemetry: false

logFilters:
  - level: discard
    text: "prettier is listed by your project with version 3.2.5, which doesn't satisfy what @xstate/cli (p68591) and other dependencies request (^2.0.0)."

nodeLinker: pnp

packageExtensions:
  "@mui/x-data-grid@*":
    peerDependencies:
      "@emotion/react": "*"
      "@emotion/styled": "*"
      "@types/react": "*"
  "@xstate/cli@*":
    peerDependencies:
      prettier: "*"
  "@xstate/tools-shared@*":
    peerDependencies:
      "@babel/core": "*"
  notistack@*:
    peerDependencies:
      csstype: "*"

yarnPath: .yarn/releases/yarn-4.3.1.cjs
