enableGlobalCache: false

enableTelemetry: false

logFilters:
  - text: prettier is listed by your project with version 3.0.3, which doesn't satisfy what @xstate/cli requests (^2.0.0).
    level: discard

nodeLinker: pnp

packageExtensions:
  "@xstate/cli@*":
    peerDependencies:
      prettier: "*"
  "@xstate/tools-shared@*":
    peerDependencies:
      "@babel/core": "*"
  notistack@*:
    peerDependencies:
      csstype: "*"

yarnPath: .yarn/releases/yarn-4.0.0-rc.53.cjs
